AbritesTask/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('webstore.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_home, name='cart_home_url'),
    path('update/', views.cart_update, name='cart_update_url'),
    path('delete/<int:cart_id>/<int:product_id>/',
         views.remove_from_cart,
         name='remove_from_cart_url'),
]

orders/urls.py
from django.urls import path

from . import views


app_name = 'orders'

urlpatterns = [
    path('create_order/', views.create_order, name='create_order_url'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Starter Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">   <link rel="icon" href="../../favicon.ico">

    <!-- Custom styles for this template -->
    <link href="starter-template.css" rel="stylesheet">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  </head>

  <body>

      <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index_url' %}">Abrites Store</a>

          <div class="collapse navbar-collapse" id="navbarsExampleDefault">
              <ul class="nav navbar-nav pull-xs-left"> </ul>

              <ul class="nav navbar-nav mx-auto">
                  <li> <a class="nav-link" href="{% url 'cart:cart_home_url' %}"><i class="fas fa-shopping-cart"></i> {{ request.session.cart_items }}</a> </li>
              </ul>

              <ul class="nav navbar-nav pull-xs-right">
                  {% if request.user.is_authenticated %}
                  <li class="nav-item"><b class="nav-link">{{user.username}}</b></li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'logout_url' %}">LogOut</a></li>
                  {% else %}
                  <li class="nav-item"><a class="nav-link" href="{% url 'signup_url' %}">Register</a></li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'login_url' %}">Login</a></li>
                  {% endif %}
              </ul>
          </div>
      </nav>

    <div class="container">

        <br />
        <br />
        <br />
        <br />

        {% block content %}
        {% endblock content %}

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </body>
</html>

templates/base_index.html
{% extends "base.html" %}


{% block content %}

    <div class="row">
        {% if all_categories or items %}
        <div class="col-md-2">
            <div class="list-group">
                <a class="btn btn-danger" href="{% url 'index_url' %}">AllProducts</a>
                {% for c in all_categories %}
                <a class='btn btn-success' href="{% url 'products_by_category_url' c.pk %}">{{ c.name }}</a>
                {% endfor %}
            </div>
        </div>

        <div class="col-md-10">
            {% block content_products %}

            {% endblock %}
        </div>

        {% else %}
    </div>
    <h2 class='text-center'>The store is empty :) </h2>
    {% endif %}

{% endblock %}

templates/cart_home.html
{% extends "base.html" %}


{% block content %}

    {% if cart.products.exists %}
        <table class="table">
        <thead>
            <tr>
            <th scope="col">#</th>
            <th scope="col">Product Name</th>
            <th scope="col">Product Price</th>
            <th scope="col">Remove</th>
            </tr>
        </thead>
        <tbody>
            {% for product in cart.products.all %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    {# <td>{{ product.name }}</td> #}
                    <td><a href="{% url 'product_detail_url' product.pk %}">{{ product.name }}</a></td>
                    <td>{{ product.price }}$</td>
                    <td> <a href="{% url 'cart:remove_from_cart_url' cart.id product.id %}" class='btn btn-danger btn-sm'>Remove</a> </td>
                </tr>
            {% endfor %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td></td>
                    <td>Total Price: <b>{{ cart.total_price }}$</b></td>
                    <td>
                        <a href="{% url 'orders:create_order_url'%}" class="btn btn-success">CheckOut!</a>
                    </td>
                </tr>
        </tbody>
        </table>
    {% else %}
        <h2 class="text-center">Cart is Empty!</h2>
    {% endif %}

{% endblock %}

templates/index.html
{% extends "base_index.html" %}
{% load thumbnail %}


{% block content_products %}

    <h3 class="text-center">All products:</h3>

    <a class='btn btn-info' href="{% url 'products_by_name_url'  %}">Order By Name</a>

    <div class="card-group">
        {% for item in items %}
            <a href="{% url 'product_detail_url' item.pk %}">
                <div class="card">
                    {% thumbnail item.image "200x200" crop="center" as im %}
                        <img src="{{ im.url }}" width="{{ im.width }}" height= "{{ im.height }}" alt="" />
                    {% endthumbnail %}
                    <div class="card-block">
                        <h4 class="card-title">{{ item.name }}</h4>
                    </div>
                    <div class="card-footer">
                        <p class="badge badge-info">Price:{{ item.price }}$</p>
                        <form action="{% url 'cart:cart_update_url' %}" method="POST" class='form'>
                            {% csrf_token %}
                            <input type="hidden" name="product_id" id="product_id" value="{{ item.id }}" />
                            {% if item in cart.products.all %}
                                <button type="submit" class="btn btn-danger">Remove</button>
                            {% else %}
                                <button type="submit" class="btn btn-success">Add To Cart</button>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>

    {% include "pagination.html" %}

{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}

    <div class="d-flex justify-content-center align-items-center container ">
        <div class="row">
            <form action="" method="POST" accept-charset="utf-8">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class='btn btn-success'>LogIn.</button>
            </form>
        </div>
    </div>

{% endblock content %}

templates/pagination.html
{% if items.has_other_pages %}

<div class="row">
    <div class="col-6 offset-3 text-center pagination-set">
        <nav aria-label="">
            <ul class="pagination justify-content-center">
                {% if items.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ items.previous_page_number }}">&laquo;</a> </li>
                {% else %}
                <li class="page-item disabled"><a class="page-link"><span>&laquo;</span></a></li>
                {% endif %}
                {% for i in page_range %}
                {% if items.number == i %}
                <li class="page-item active"><a class="page-link" href="#">{{ i }} <span
                        class="sr-only">(current)</span></a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% endfor %}
                {% if items.has_next %}
                <li class="page-item"><a class="page-link" aria-label="Next" href="?page={{ items.next_page_number }}">&raquo;</a></li>
                {% else %}
                <li class="page-item disabled"><a class="page-link"><span>&raquo;</span></a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>

{% endif %}

templates/product_detail.html
{% extends "base.html" %}


{% block content %}
    <div class="row">
        <div class="card card-inverse" style="background-color: #333; border-color: #333;">
            <img class="card-img-top" src="{{ MEDIA_URL }}{{ product.image }}" alt="{{ product.name }}">
            <div class="card-block mx-auto text-center">
                <strong><h2 class="card-title">{{ product.name }}</h2></strong>
                <p class="card-text">{{ product.description }}</p>
                <h3>
                    Price: <span class="badge badge-info">{{ product.price }}$</span>
                </h3>
            </div>

            <div class='mx-auto text-center'>
                <form action="{% url 'cart:cart_update_url'%}" method="POST" class='form'>
                    {% csrf_token %}
                    <input type="hidden" name="product_id" id="product_id" value="{{ product.id }}" />
                    {% if product in cart.products.all %}
                        <button type="submit" class="btn btn-danger">Remove From Cart</button>
                    {% else %}
                        <button type="submit" class="btn btn-success">Add To Cart</button>
                    {% endif %}
                </form>
                <br />
                <br />
                <br />
            </div>
        </div>
    </div>
{% endblock content %}

templates/products_by_category.html
{% extends "base_index.html" %}
{% load thumbnail %}


{% block content_products %}

    <h2 class="text-center"> Category: {{ category }}</h2>

    <a class='btn btn-info' href="{% url 'products_in_cat_by_name_url' category.pk %}">Order By Name</a>

    <div class="card-group">
        {% for item in items %}
            <a href="{% url 'product_detail_url' item.pk %}">
                <div class="card">
                    {% thumbnail item.image "200x200" crop="center" as im %}
                        <img src="{{ im.url }}" width="{{ im.width }}" height= "{{ im.height }}" alt="" />
                    {% endthumbnail %}
                    <div class="card-block">
                        <h4 class="card-title">{{ item.name }}</h4>
                    </div>
                    <div class="card-footer">
                        <p class="badge badge-info">Price:{{ item.price }}$</p>
                        <form action="{% url 'cart:cart_update_url' %}" method="POST" class='form'>
                            {% csrf_token %}
                            <input type="hidden" name="product_id" id="product_id" value="{{ item.id }}" />
                            {% if item in cart.products.all %}
                                <button type="submit" class="btn btn-danger">Remove</button>
                            {% else %}
                                <button type="submit" class="btn btn-success">Add To Cart</button>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>

    {% include "pagination.html" %}


{% endblock %}

templates/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="d-flex justify-content-center align-items-center container ">
        <div class="row">
            <form action="" method="POST" accept-charset="utf-8">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class='btn btn-success'>SignUp</button>
            </form>
        </div>
    </div>
{% endblock content %}

templates/thank_you_for_order.html
{% extends "base.html" %}


{% block content %}
    <h2 class="text-center">Thank you for your order {{ order.user }} </h2>
{% endblock %}